# Generated by Django 4.0.4 on 2022-05-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seguimiento',
            table='db_seguimiento',
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='db_tipo_usuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='db_usuario',
        ),
    ]
