# Generated by Django 4.0.4 on 2022-04-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipousuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
                ('hora_pedido', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('recibido', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
