from django.urls import path
from .views import *

urlpatterns = [
    path('',index, name="index"),
    path('index',index, name="index"),
    path('productos',productos, name="productos"),
    path('indexRegistrado',indexRegistrado, name="indexRegistrado"),
    path('indexSuscrito',indexSuscrito, name="indexSuscrito"),
    path('inicio',inicio, name="inicio"),
    path('planes',planes, name="planes"),
    path('productoRegistrado',productoRegistrado, name="productoRegistrado"),
    path('productoSuscrito',productoSuscrito, name="productoSuscrito"),
    path('registro',registro, name="registro"),
    path('seguimiento',seguimiento, name="seguimiento"),
    path('seguimientoSuscrito',seguimientoSuscrito, name="seguimientoSuscrito"),
    path('carrito',carrito, name="carrito"),
    path('carritoDesc',carritoDesc, name="carritoDesc"),
    path('carritoNR',carritoNR, name="carritoNR"),
    path('base',base, name="base"),
    path('historialdecompras',historialdecompras, name="historialdecompras"),
    path('agregar_producto',agregar_producto, name="agregar_producto"),
    path('modificarProducto/<codigo>/',modificarProducto, name="modificarProducto"),
    path('listarProductos',listarProductos, name="listarProductos"),
    path('eliminarProducto/<codigo>/',eliminarProducto, name="eliminarProducto"),
    path('agregar_usuario/',agregar_usuario, name="agregar_usuario"),
    path('listarUsuarios/',listarUsuarios, name="listarUsuarios"),
    path('modificarUsuario/<id>/',modificarUsuario, name="modificarUsuario"),
    path('eliminarUsuario/<id>/',eliminarUsuario, name="eliminarUsuario"),
]