from django.urls import path
from .views import *

urlpatterns = [
    path('',index, name="index"),
    path('index/',index, name="index"),
    path('productos/',productos, name="productos"),
    path('indexRegistrado',indexRegistrado, name="indexRegistrado"),
    path('indexSuscrito/',indexSuscrito, name="indexSuscrito"),
    path('inicio/',inicio, name="inicio"),
    path('planes',planes, name="planes"),
    path('productoSuscrito',productoSuscrito, name="productoSuscrito"),
    path('productoRegistrado/',productosRegistrados, name="productoRegistrado"),
    path('registro',registro, name="registro"),
    path('seguimiento/',seguimiento, name="seguimiento"),
    path('seguimientoSuscrito/',seguimientoSuscrito, name="seguimientoSuscrito"),
    path('carrito/',Carro, name="Carro"),
    path('carritoDesc/',carritoDesc, name="carritoDesc"),
    path('base/',base, name="base"),
    path('historialdecompras/',historialdecompras, name="historialdecompras"),
    path('historialsuscrito/',historialsuscrito, name="historialsuscrito"),
    path('agregar/',agregar_producto, name="agregar_producto"),
    path('modificarProducto/<codigo>/',modificarProducto, name="modificarProducto"),
    path('listar/',listarProductos, name="listarProductos"),
    path('eliminarProducto/<codigo>/',eliminarProducto, name="eliminarProducto"),
    path('agregar_usuario/',agregar_usuario, name="agregar_usuario"),
    path('listarusuarios/',listarUsuarios, name="listarUsuarios"),
    path('modificarUsuario/<codigo>/',modificarUsuario, name="modificarUsuario"),
    path('eliminarUsuario/<codigo>/',eliminarUsuario, name="eliminarUsuario"),
    path('finalizado/',delete_product, name="delete_product"),
    path('finalizadoSuscrito/',delete_product_suscrito, name="delete_product_suscrito"),
]